In [ ]:
# !pip install pycaret

In [1]:
from pycaret.datasets import get_data
data1 = get_data(dataset = "traffic")

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,Rush Hour,traffic_volume
0,None,288.28,0.0,0.0,40,Clouds,1,5545
1,None,289.36,0.0,0.0,75,Clouds,0,4516
2,None,289.58,0.0,0.0,90,Clouds,0,4767
3,None,290.13,0.0,0.0,90,Clouds,0,5026
4,None,291.14,0.0,0.0,75,Clouds,0,4918

In [2]:
from pycaret.regression import *

In [3]:
dataset = setup(data = data1, target = "traffic_volume", session_id = 438)

In [4]:
best = compare_models()

In [ ]:
tuned_best = tune_model(estimator = best)

,,
,,
Initiated,. . . . . . . . . . . . . . . . . .,23:10:13
Status,. . . . . . . . . . . . . . . . . .,Searching Hyperparameters
Estimator,. . . . . . . . . . . . . . . . . .,Light Gradient Boosting Machine

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits